import { BaseCommand, CommandOptions } from '../../structures/BaseCommand';
import { ChatInputCommandInteraction, Message, EmbedBuilder } from 'discord.js';
import { COLORS, EMOJIS } from '../../utils/Constants';

export class FortuneCommand extends BaseCommand {
  constructor() {
    const options: CommandOptions = {
      name: 'fortune',
      description: 'Get a random fortune cookie message',
      category: 'fun',
      cooldown: 5,
      userPermissions: [],
      botPermissions: [],
      guildOnly: false,
      slashCommand: true,
      prefixCommand: true,
      aliases: ['fortunecookie', 'cookie'],
      examples: ['/fortune', 'p!fortune'],
    };
    super(options);
  }

  private fortunes = [
    'A beautiful, smart, and loving person will be coming into your life.',
    'A dubious friend may be an enemy in camouflage.',
    'A faithful friend is a strong defense.',
    'A fresh start will put you on your way.',
    'A golden egg of opportunity falls into your lap this month.',
    'A lifetime of happiness lies ahead of you.',
    'A pleasant surprise is waiting for you.',
    'A short pencil is usually better than a long memory.',
    'A small donation is call for. It\'s the right thing to do.',
    'A smile is your passport into the hearts of others.',
    'Adventure can be real happiness.',
    'All the effort you are making will ultimately pay off.',
    'Allow compassion to guide your decisions.',
    'An acquaintance of the past will affect you in the near future.',
    'Believe in yourself and others will too.',
    'Carve your name on your heart and not on marble.',
    'Change is happening in your life, so go with the flow!',
    'Distance yourself from the vain.',
    'Don\'t be discouraged, because every wrong attempt discarded is another step forward.',
    'Don\'t confuse recklessness with confidence.',
    'Expect much of yourself and little of others.',
    'Failure is the chance to do better next time.',
    'Fear less, hope more.',
    'Happiness will bring you good luck.',
    'Have a beautiful day.',
    'He who knows he has enough is rich.',
    'Help! I\'m being held prisoner in a fortune cookie factory!',
    'If your desires are not extravagant, they will be granted.',
    'If your desires are not to extravagant they will be granted.',
    'It is better to deal with problems before they arise.',
    'Let the deeds speak.',
    'Listen not to vain words of empty tongues.',
    'Listen to everyone. Ideas come from everywhere.',
    'Living with a commitment to excellence shall take you far.',
    'Long life is in store for you.',
    'Love is a warm fire to keep the soul warm.',
    'Love is like sweet medicine, good to the last drop.',
    'Man is born to live and not to prepare to live.',
    'Many will travel to hear you speak.',
    'Meditation with an old enemy is advised.',
    'Never fear! The end of something marks the start of something new.',
    'New ideas could be profitable.',
    'New people will bring you new realizations.',
    'No one can walk backward into the future.',
    'Nothing is more difficult, and therefore more precious, than to be able to decide.',
    'Now is a good time to buy stock.',
    'Now is the time to go ahead and pursue that love interest!',
    'Now is the time to try something new.',
    'Observe all men, but most of all yourself.',
    'One can never fill another\'s shoes, rather he must outgrow the old shoes.',
    'One of the first things you should look for in a problem is its positive side.',
    'Others can help you now.',
    'Pennies from heaven find their way to your doorstep this year!',
    'People are attracted by your Delicate features.',
    'People find it difficult to resist your persuasive manner.',
    'Perhaps you\'ve been focusing too much on saving.',
    'Physical activity will dramatically improve your outlook today.',
    'Practice makes perfect.',
    'Protective measures will prevent costly disasters.',
    'Put your mind into planning today. Look into the future.',
    'Remember the birthday but never the age.',
    'Remember to share good fortune as well as bad with your friends.',
    'Rest has a peaceful effect on your physical and emotional health.',
    'Resting well is as important as working hard.',
    'Romance moves you in a new direction.',
    'Savor your freedom - it is precious.',
    'Say hello to others. You will have a happier day.',
    'Share your joys and sorrows with your family.',
    'Sloth makes all things difficult; industry all easy.',
    'Small confidences mark the beginning of a friendship.',
    'Society prepares the crime; the criminal commits it.',
    'Someone you care about seeks reconciliation.',
    'Soon life will become more interesting.',
    'Stand tall. Don\'t look down upon yourself.',
    'Staying close to home is going to be best for your morale today.',
    'Stop searching forever, happiness is just next to you.',
    'Success is a journey, not a destination.',
    'Success is failure turned inside out.',
    'Success is going from failure to failure without loss of enthusiasm.',
    'Swimming with the current is faster.',
    'Take care and sensitivity you show towards others will return to you.',
    'Take the high road.',
    'Technology is the art of arranging the world so we don\'t have to experience it.',
    'The austerity you see around you covers the richness of life like a veil.',
    'The best prediction of future is the past.',
    'The change you started already have far-reaching effects. Be ready.',
    'The first man gets the oyster, the second man gets the shell.',
    'The harder you work, the luckier you get.',
    'The night life is for you.',
    'The one that recognizes the illusion does not act as if it is real.',
    'The only people who never fail are those who never try.',
    'The person who will not stand for something will fall for anything.',
    'The philosophy of one century is the common sense of the next.',
    'The saints are the sinners who keep on trying.',
    'The secret to getting ahead is getting started.',
    'The small courtesies sweeten life. The greater ennoble it.',
    'The smart thing to do is to begin trusting your intuitions.',
    'The strong person understands how to withstand substantial loss.',
    'The sure way to predict the future is to invent it.',
    'The truly generous share, even with the undeserving.',
    'The value lies not within any particular thing, but in the desire placed on that thing.',
    'There is no mistake so great as that of being always right.',
    'There is no wisdom greater than kindness.',
    'Those who care will make the effort.',
    'Time and patience are called for many surprises await you!',
    'Time is precious, but truth is more precious than time.',
    'To know oneself, one should assert oneself.',
    'Today is the tomorrow we worried about yesterday.',
    'Use your eloquence where it will do the most good.',
    'Welcome change.',
    'Well done is better than well said.',
    'What\'s hidden in an empty box?',
    'What\'s yours is mine, and what\'s mine is mine.',
    'When more become too much. It is same as being not enough.',
    'When your heart is pure, your mind is clear.',
    'Wish you happiness.',
    'You always bring others happiness.',
    'You are a person of another time.',
    'You are a talented storyteller.',
    'You are admired by everyone for your talent and ability.',
    'You are almost there.',
    'You are busy, but you are happy.',
    'You are generous to an extreme and always think of the other fellow.',
    'You are going to have some new clothes.',
    'You are in good hands this evening.',
    'You are interested in higher education, whether material or spiritual.',
    'You are modest and courteous.',
    'You are never selfish with your advice or your help.',
    'You are next in line for promotion in your firm.',
    'You are offered the dream of a lifetime. Say yes!',
    'You are open-minded and quick to make new friends.',
    'You are solid and dependable.',
    'You are soon going to change your present line of work.',
    'You are talented in many ways.',
    'You are the master of every situation.',
    'You are very grateful for the small pleasures of life.',
    'You are working hard.',
    'You can keep a secret.',
    'You cannot become rich except by enriching others.',
    'You cannot love life until you live the life you love.',
    'You have a deep appreciation of the arts and music.',
    'You have a deep interest in all that is artistic.',
    'You have a friendly heart and are well admired.',
    'You have a shrewd knack for spotting insincerity.',
    'You have a yearning for perfection.',
    'You have an active mind and a keen imagination.',
    'You have an ambitious nature.',
    'You have an unusual equipment for success, use it properly.',
    'You have exceeded what was expected.',
    'You have the power to write your own fortune.',
    'You have yearning for perfection.',
    'You know where you are going and how to get there.',
    'You look pretty.',
    'You love challenge.',
    'You love peace.',
    'You make people realize that there are great beauties in this world.',
    'You might be looking for a new job.',
    'You never hesitate to tackle the most difficult problems.',
    'You will always get what you want through your charm and personality.',
    'You will be always surrounded by true friends.',
    'You will be blessed with longevity.',
    'You will be pleasantly surprised tonight.',
    'You will be sharing great news with all the people you love.',
    'You will become more and more wealthy.',
    'You will enjoy good health.',
    'You will enjoy good health; you will be surrounded by luxury.',
    'You will find great contentment in the daily, routine activities.',
    'You will have a fine capacity for the enjoyment of life.',
    'You will have gold pieces by the bushel.',
    'You will inherit a large sum of money.',
    'You will make change for the better.',
    'You will soon be surrounded by good friends and laughter.',
    'You will take a chance in something in near future.',
    'Your ability for accomplishment will follow with success.',
    'Your ability to juggle many tasks will take you far.',
    'Your biggest virtue is your modesty.',
    'Your capacity for learning is inspiring.',
    'Your character can be described as enthusiastically rival.',
    'Your high-minded principles spell success.',
    'Your hard work will pay off in a manner you never expected.',
    'Your home is the center of great love.',
    'Your ideals are well within your reach.',
    'Your infinite capacity for patience will be rewarded.',
    'Your leadership qualities will be tested and proven.',
    'Your life will be happy and peaceful.',
    'Your life will get more and more exciting.',
    'Your love life will be happy and harmonious.',
    'Your love of music will be an important part of your life.',
    'Your mind is your greatest asset.',
    'Your moods signal a period of change.',
    'Your quick wits will get you out of a tight spot.',
    'Your success will astonish everyone.',
    'Your talents will be recognized and rewarded.',
    'Your work interests can capture the highest status or prestige.',
  ];

  public async executeSlash(interaction: ChatInputCommandInteraction): Promise<void> {
    const fortune = this.fortunes[Math.floor(Math.random() * this.fortunes.length)];

    const embed = new EmbedBuilder()
      .setTitle(`${EMOJIS.fun} Fortune Cookie`)
      .setColor(COLORS.info)
      .setDescription(`🥠 ${fortune}`)
      .setTimestamp();

    await interaction.reply({ embeds: [embed] });
  }

  public async executePrefix(message: Message): Promise<void> {
    const fortune = this.fortunes[Math.floor(Math.random() * this.fortunes.length)];

    const embed = new EmbedBuilder()
      .setTitle(`${EMOJIS.fun} Fortune Cookie`)
      .setColor(COLORS.info)
      .setDescription(`🥠 ${fortune}`)
      .setTimestamp();

    await message.reply({ embeds: [embed] });
  }
}

export default FortuneCommand;
