import { BaseCommand, CommandOptions } from '../../structures/BaseCommand';
import { ChatInputCommandInteraction, Message, EmbedBuilder, SlashCommandBuilder } from 'discord.js';
import { PanindiganClient } from '../../structures/PanindiganClient';
import { COLORS, EMOJIS } from '../../utils/Constants';

export class EmbedAiCommand extends BaseCommand {
  constructor() {
    super({
      name: 'embedai',
      description: 'Generate rich embed content using AI for a given topic (Diamond+)',
      category: 'ai',
      premiumTier: 'diamond',
      cooldown: 20,
      ownerOnly: false,
      guildOnly: false,
      slashCommand: true,
      prefixCommand: true,
      aliases: ['aiembed', 'generateembed'],
      examples: ['/embedai topic:History of the Internet', 'p!embedai History of the Internet'],
    } as CommandOptions);
  }

  public buildSlashCommand(): SlashCommandBuilder {
    return new SlashCommandBuilder()
      .setName(this.name)
      .setDescription(this.description)
      .addStringOption(o =>
        o.setName('topic').setDescription('Topic to generate embed content for').setRequired(true).setMaxLength(200)
      )
      .setDMPermission(false) as SlashCommandBuilder;
  }

  public async executeSlash(i: ChatInputCommandInteraction): Promise<void> {
    const topic = i.options.getString('topic', true);
    await i.deferReply();
    try {
      const client = i.client as PanindiganClient;
      const prompt = `Generate structured Discord embed content about the topic: "${topic}"

Respond in this exact format:
TITLE: [compelling title]
DESCRIPTION: [2-3 sentence overview]
FIELD1_NAME: [section heading]
FIELD1_VALUE: [content, max 200 chars]
FIELD2_NAME: [section heading]
FIELD2_VALUE: [content, max 200 chars]
FIELD3_NAME: [section heading]
FIELD3_VALUE: [content, max 200 chars]
FOOTER: [brief interesting fact or source note]`;

      const response = await client.aiHandler.generateTaskResponse(topic, prompt);

      // Parse structured response
      const lines = response.content.split('\n');
      const get = (key: string) => lines.find(l => l.startsWith(`${key}:`))?.replace(`${key}:`, '').trim() || '';

      const embed = new EmbedBuilder()
        .setTitle(get('TITLE') || topic)
        .setColor(COLORS.diamond)
        .setDescription(get('DESCRIPTION') || response.content.slice(0, 300))
        .setFooter({ text: get('FOOTER') || `Generated by AI • ${response.provider}` })
        .setTimestamp();

      const f1n = get('FIELD1_NAME'); const f1v = get('FIELD1_VALUE');
      const f2n = get('FIELD2_NAME'); const f2v = get('FIELD2_VALUE');
      const f3n = get('FIELD3_NAME'); const f3v = get('FIELD3_VALUE');

      if (f1n && f1v) embed.addFields({ name: f1n, value: f1v, inline: true });
      if (f2n && f2v) embed.addFields({ name: f2n, value: f2v, inline: true });
      if (f3n && f3v) embed.addFields({ name: f3n, value: f3v, inline: false });

      await i.editReply({ embeds: [embed] });
    } catch (err: any) {
      await i.editReply({ content: `${EMOJIS.error} Error: ${err.message || 'AI unavailable.'}` });
    }
  }

  public async executePrefix(m: Message, args: string[]): Promise<void> {
    const topic = args.join(' ');
    if (!topic) return void m.reply(`${EMOJIS.error} Please provide a topic. Example: \`p!embedai History of the Internet\``);

    const thinking = await m.reply(`${EMOJIS.ai} Generating embed content for **${topic}**...`);
    try {
      const client = m.client as PanindiganClient;
      const response = await client.aiHandler.generateTaskResponse(
        topic,
        `Generate a rich overview of: "${topic}". Include a title, brief description, 3 key sections with headings, and an interesting footer fact.`
      );

      const embed = new EmbedBuilder()
        .setTitle(`📄 ${topic}`)
        .setColor(COLORS.diamond)
        .setDescription(response.content.slice(0, 4000))
        .setFooter({ text: `Provider: ${response.provider}` })
        .setTimestamp();

      await thinking.edit({ content: null, embeds: [embed] });
    } catch (err: any) {
      await thinking.edit(`${EMOJIS.error} Error: ${err.message || 'AI unavailable.'}`);
    }
  }
}

export default EmbedAiCommand;
