import { BaseCommand, CommandOptions } from '../../structures/BaseCommand';
import { ChatInputCommandInteraction, Message, EmbedBuilder, SlashCommandBuilder } from 'discord.js';
import { PanindiganClient } from '../../structures/PanindiganClient';
import { COLORS, EMOJIS } from '../../utils/Constants';

export class ImageCommand extends BaseCommand {
  constructor() {
    const options: CommandOptions = {
      name: 'image',
      description: 'Generate an AI image using DALL-E (requires OpenAI key)',
      category: 'ai',
      premiumTier: 'bronze',
      cooldown: 30,
      userPermissions: [],
      botPermissions: [],
      guildOnly: false,
      slashCommand: true,
      prefixCommand: true,
      aliases: ['aiimage', 'dalle'],
      examples: ['/image A sunset over Manila Bay, digital art', 'p!image A cute capybara in a flower field'],
    };
    super(options);
  }

  public buildSlashCommand(): SlashCommandBuilder {
    return new SlashCommandBuilder()
      .setName(this.name)
      .setDescription(this.description)
      .addStringOption(o => o.setName('prompt').setDescription('Image description').setRequired(true))
      .addStringOption(o => o.setName('style').setDescription('Art style hint').setRequired(false)
        .addChoices(
          { name: 'Digital art', value: 'digital art' },
          { name: 'Photorealistic', value: 'photorealistic' },
          { name: 'Anime/Manga', value: 'anime style' },
          { name: 'Oil painting', value: 'oil painting' },
          { name: 'Watercolor', value: 'watercolor' }
        )) as SlashCommandBuilder;
  }

  public async executeSlash(interaction: ChatInputCommandInteraction): Promise<void> {
    const prompt = interaction.options.getString('prompt', true);
    const style = interaction.options.getString('style') || '';
    await interaction.deferReply();
    try {
      const client = interaction.client as PanindiganClient;
      const fullPrompt = style ? `${prompt}, ${style}` : prompt;
      const imageUrl = await client.aiHandler.generateImage(fullPrompt);
      if (!imageUrl) {
        await interaction.editReply({ content: `${EMOJIS.error} Failed to generate image. Make sure OpenAI API key is configured.` });
        return;
      }
      const embed = new EmbedBuilder()
        .setTitle(`${EMOJIS.ai} 🎨 AI Image Generated`)
        .setColor(COLORS.primary)
        .setDescription(`**Prompt:** ${prompt}${style ? `\n**Style:** ${style}` : ''}`)
        .setImage(imageUrl)
        .setFooter({ text: 'Generated by DALL-E 3 | Panindigan AI' })
        .setTimestamp();
      await interaction.editReply({ embeds: [embed] });
    } catch (err: any) {
      const isLimitErr = err.message?.includes('not available') || err.message?.includes('daily limit');
      await interaction.editReply({
        content: `${EMOJIS.error} ${isLimitErr ? 'Image generation requires Bronze+ premium or daily limit reached.' : `Error: ${err.message || 'Failed to generate image.'}`}`
      });
    }
  }

  public async executePrefix(message: Message, args: string[]): Promise<void> {
    const prompt = args.join(' ');
    if (!prompt) return void message.reply(`${EMOJIS.error} Please provide an image description.`);
    const thinking = await message.reply(`${EMOJIS.ai} Generating image... ⏳`);
    try {
      const client = message.client as PanindiganClient;
      const imageUrl = await client.aiHandler.generateImage(prompt);
      if (!imageUrl) {
        await thinking.edit(`${EMOJIS.error} Failed to generate image. Make sure OpenAI API key is configured.`);
        return;
      }
      const embed = new EmbedBuilder()
        .setTitle(`${EMOJIS.ai} 🎨 AI Image Generated`)
        .setColor(COLORS.primary)
        .setDescription(`**Prompt:** ${prompt}`)
        .setImage(imageUrl)
        .setFooter({ text: 'Generated by DALL-E 3 | Panindigan AI' })
        .setTimestamp();
      await thinking.edit({ content: null, embeds: [embed] });
    } catch (err: any) {
      await thinking.edit(`${EMOJIS.error} Error: ${err.message || 'Failed to generate image.'}`);
    }
  }
}

export default ImageCommand;
